# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  
  pod 'TestSdk', :git => 'https://github.com/longpham2310/TestSdk.git'
end


target 'DemoSdk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  
  pod 'ZIPFoundation'
end
